swagger: "2.0"
info:
  version: 1.0.0
  title: Typescript Swagger REST API
  license:
    name: MIT
  contact:
    email: "maciej.jarkowski@pl.ibm.com"
host: "localhost:8080"
basePath: "/api/v1"
schemes:
- "http"
- "https"
securityDefinitions:
  BasicAuth:
    type: basic
paths:
  /echo:
    post:
      x-swagger-router-controller: Test
      summary: Echo request.msg to response. 
      operationId: echo
      tags:
        - Test
      consumes:
      - "application/json"
      produces:
      - "application/json"
      security:
        - BasicAuth: []
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/EchoRequest"
      responses:
        200:
          description: Echo response
          schema:
            $ref: "#/definitions/EchoResponse"
        default:
          description: Unexpected error
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  EchoRequest:
    type: object
    properties:
      msgIn:
        type: string
    required:
      - msgIn
  EchoResponse:
    type: object
    properties:
      msgOut:
        type: string
    required:
      - msgOut
  ErrorResponse:
    type: object
    properties:
      error:
        type: string
    required:
      - error
